ecommerceproject/ecommerceapp/urls.py
from django.urls import path
from . import views

app_name = "ecommerceapp"

urlpatterns = [
    path('',views.index,name="index"),
    path('about/', views.about, name="about"),
    path('signup/',views.SignUpView.as_view(), name="signup"),
    path('electronic/', views.electronic_page, name="electronic"),
    path('clothes/', views.clothes_page, name="clothes"),
    path('homeappliances/', views.home_appliances_page, name="homeappliances"),
    path('cosmetic/', views.cosmetic_page, name="cosmetic"),
    path('sportandoutdoor/', views.sport_outdoor_page, name="sportandoutdoor"),
    path('carpart/', views.car_part_page, name="carpart"),
    path('gardenequipment/', views.garden_equipment_page, name="gardenequipment"),
    path('detail/<int:pk>', views.detail,name="detail"),
    path('addbuyitem/<int:pk>', views.addbuyitem, name="addbuyitem"),
    path('cart/',views.cart,name="cart"),
    path('deletecart/<int:pk>', views.deletecart, name="deletecart"),
    path('payment/', views.payment, name="payment"),
    path('order/', views.order, name="order"),
]

ecommerceproject/ecommerceproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("",include('ecommerceapp.urls')),
    path("", include('django.contrib.auth.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerceproject/templates/base.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
    <link rel="stylesheet"href="https://fonts.googleapis.com/css?family=Kanit">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Pacifico">
    <title>E-commerce</title>

    <style>
    .flexMain {
      display:flex;
      align-items: center
    }
    .flex1 { flex:1 }
    .flex2 { flex:2 }
    .flex3 { flex:3 }
    
    button.siteLink {
      margin-left:-5px;
      border:none;
      padding:24px;
      display:inline-block;
      min-width:115px;
    }
    .whiteLink {
      background : #fff;
    }
    .whiteLink:active {
      background : #000;
      color: #fff;
    }
    .blackLink {
      color: #fff;
      background:#232323;
      transition: all 300ms linear;
    }
    
    .blackLink:active {
      color: #000;
      background:#fff
    }
    #siteBrand {
      font-family: impact;
      letter-spacing : -1px;
      font-size:32px;
      color:#252525;
      line-height : 1em;
    }
    #menuDrawer {
      background:#fff;
      position:fixed;
      height:100vh;
      overflow:auto;
      z-index:12312;
      top:0;
      left:0;
      border-right:1px solid #eaeaea;
      min-width:25%;
      max-width:320px;
      width:100%;
      transform : translateX(-100%);
      transition : transform 200ms linear;
    }
    #mainNavigation {
      transition : transform 200ms linear;
      background : #fff;
    }
    .drawMenu > #menuDrawer {
      transform : translateX(0%);
    }
    .drawMenu > #mainNavigation {
      transform : translateX(25%);
    }
    .fa-times {
      cursor : pointer
    }
    a.nav-menu-item:hover {
      margin-left:2px;
      border-left:10px solid black;
    }
    a.nav-menu-item{
      transition:border 200ms linear;
      text-decoration:none;
      display:block;
      padding:18px;
      padding-left:32px;
      border-bottom:1px solid #eaeaea;
      font-weight:bold;
      color:#343434
    }
    select.noStyle {
      border:none;
      outline:none
    }

    #seconde-navbar{
      padding: 10px;
      font-family: Kanit ;
      text-align: center;
      padding-left: 30%;
      
    }
    
    a:link {
         color: deepskyblue;
         background-color: transparent;
         text-decoration: none;
      }
      a:visited {
         color: deepskyblue;
         background-color: transparent;
         text-decoration: none;
      }
      a:active {
         color: yellow;
         background-color: transparent;
      }

      hr {
  margin-top: 1rem;
  margin-bottom: 1rem;
  border: 1;
  border-top: 1px solid rgba(0, 0, 0, 0.89);
}  
.search-button{
  background-color: black;
  border: none;
  color: white;
  padding: 10px 20px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  margin: 4px 2px;
  cursor: pointer;
  border-radius: 16px;
}
.search-button:hover{
  background-color: #f1f1f1;
}

#denem{
  width: 15px;
  padding: 2px;
  margin-left: 1px;
  height: 62px;

}




.badge {
  padding-left: 9px;
  padding-right: 9px;
  -webkit-border-radius: 9px;
  -moz-border-radius: 9px;
  border-radius: 9px;
}

.label-warning[href],
.badge-warning[href] {
  background-color: #c67605;
}
#lblCartCount {
    font-size: 12px;
    background: deepskyblue;
    color: #fff;
    padding: 0 5px;
    vertical-align: top;
    margin-left: -10px; 
}
  

</style>
  
</head>
<body>

  
  <div class="p-3 bg-dark text-white">
    <div class="flexMain">
      <div class="flex1">
  
      </div>
      <div class="flex2 text-center">
        <div><strong>Now is the time to buy something, right? 😏</strong></div>     
      </div>
      <div class="flex1">
      </div>
    </div>
  </div>
  <div id="menuHolder">
    <div role="navigation" class="sticky-top border-bottom border-top" id="mainNavigation">
      <div class="flexMain">
        <div class="flex2" >
          {% if request.user.is_authenticated %}
           <h4 style="font-size:larger;  width: 260px; margin-left: 10px; padding: 5px; font-family: Pacifico;">Welcome, {{user.username}}</h4>
          {% else %}    
          {% endif %}
        </div>
        <div class="flex3 text-center" id="siteBrand">
          <a href="{% url 'ecommerceapp:index' %}" style="color: #000;">E-commerce website</a>
        </div>
  
        <div class="flex2 text-end d-block d-md-none">
          <button class="whiteLink siteLink"><i class="fas fa-search"></i></button>
        </div>
  
        <div class="flex2 text-end d-none d-md-block">
          {% if request.user.is_authenticated %}
          <a href="{% url 'ecommerceapp:cart' %}"><button class="whiteLink siteLink" style="height: 72px;"><i class="fa fa-shopping-cart" style="font-size:19px;"></i></button></a>
        
          <a href="{% url 'logout' %}?next=/"><button class="blackLink siteLink">Logout</button></a>        
          {% else %}
          <a href="{% url 'ecommerceapp:signup' %}"><button class="whiteLink siteLink">REGISTER</button></a> 
          <a href="{% url 'login' %}"><button class="blackLink siteLink">Login</button></a>
          {% endif %}

        </div>
      </div>
    </div>
  </div>

  <div class="nav-scroller bg-body shadow-sm" id="seconde-navbar">
    <nav class="nav" aria-label="Secondary navigation">
      <a class="nav-link" href="{% url 'ecommerceapp:electronic' %}">Electronic</a>
      <a class="nav-link" href="{% url 'ecommerceapp:clothes' %}">Clothes</a>
      <a class="nav-link" href="{% url 'ecommerceapp:homeappliances' %}">Home Appliances</a>
      <a class="nav-link" href="{% url 'ecommerceapp:cosmetic' %}">Cosmetic</a>
      <a class="nav-link" href="{% url 'ecommerceapp:sportandoutdoor' %}">Sports&Outdoor</a>
      <a class="nav-link" href="{% url 'ecommerceapp:carpart' %}">Car Parts</a>
      <a class="nav-link" href="{% url 'ecommerceapp:gardenequipment' %}">Garden Equipment</a>
    </nav>
  </div>
  
  {%block content%}

  {%endblock%}
  

  
  
</body>
</html>