ecommerceproject/ecommerceapp/urls.py
from django.urls import path
from . import views

app_name = "ecommerceapp"

urlpatterns = [
    path('',views.index,name="index"),
    path('about/', views.about, name="about"),
    path('signup/',views.SignUpView.as_view(), name="signup"),
    path('electronic/', views.electronic_page, name="electronic"),
    path('clothes/', views.clothes_page, name="clothes"),
    path('homeappliances/', views.home_appliances_page, name="homeappliances"),
    path('cosmetic/', views.cosmetic_page, name="cosmetic"),
    path('sportandoutdoor/', views.sport_outdoor_page, name="sportandoutdoor"),
    path('carpart/', views.car_part_page, name="carpart"),
    path('gardenequipment/', views.garden_equipment_page, name="gardenequipment"),
    path('detail/<int:pk>', views.detail,name="detail"),
    path('addbuyitem/<int:pk>', views.addbuyitem, name="addbuyitem"),
    path('cart/',views.cart,name="cart"),
    path('deletecart/<int:pk>', views.deletecart, name="deletecart"),
    path('payment/', views.payment, name="payment"),
    path('order/', views.order, name="order"),
]

ecommerceproject/ecommerceproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("",include('ecommerceapp.urls')),
    path("", include('django.contrib.auth.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerceproject/ecommerceapp/models.py
from django.db import models

# Create your models here.

class ProductsOnSale(models.Model):
    companyname = models.CharField(max_length=50)
    productType = models.CharField(max_length=30)
    productName = models.CharField(max_length=100)
    productPrice = models.FloatField()
    productdescription = models.CharField(max_length=800)
    creationDate = models.DateTimeField(auto_now_add= True)
    product_image = models.FileField(blank=True)

    def __str__(self):
        return f"{self.companyname} --> {self.productName} "


class Buyitem(models.Model):
    item_pk = models.IntegerField()
    who_buy = models.CharField(max_length=50)
    def __str__(self):
        return f"{self.who_buy} --> {self.item_pk} "
    
class OrderForm(models.Model):
    first_name= models.CharField(max_length=50)
    Last_name= models.CharField(max_length=50)
    username= models.CharField(max_length=50)
    email= models.CharField(max_length=50)
    address1= models.CharField(max_length=50)
    address2= models.CharField(max_length=50, null=True)
    country= models.CharField(max_length=50)
    state= models.CharField(max_length=50)
    zip= models.CharField(max_length=50)
    payment= models.CharField(max_length=50)
    name_on_card= models.CharField(max_length=50)
    credit_card_number= models.CharField(max_length=50)
    expiration= models.CharField(max_length=50)
    CVV= models.CharField(max_length=50)
    price= models.CharField(max_length=50)
    ordered_items_pk= models.CharField(max_length=400)

    def __str__(self):
        return f"{self.email} --> {self.price} $ --> {self.username} "

ecommerceproject/ecommerceapp/views.py
from django.shortcuts import render, redirect
from django.urls import reverse, reverse_lazy
from . import models
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.contrib.auth.forms import UserCreationForm
from django.views.generic import CreateView
from django.contrib import messages

# Create your views here.

def index(request):
    return render(request,"ecommerceapp/mainscreen.html")


def about(request):
    return render(request,"ecommerceapp/about.html")


def electronic_page(request):
    electronic_items = models.ProductsOnSale.objects.filter(Q(productType="Electronic")).all()
    electronic_items_dict={"electronic_items": electronic_items}
    return render(request,'ecommerceapp/electronic.html', context=electronic_items_dict)


def clothes_page(request):
    clothes_items = models.ProductsOnSale.objects.filter(Q(productType="Clothes")).all()
    clothes_items_dict={"clothes_items": clothes_items}
    return render(request,'ecommerceapp/clothes.html', context=clothes_items_dict)


def home_appliances_page(request):
    home_appliances_items = models.ProductsOnSale.objects.filter(Q(productType="Home Appliances")).all()
    home_appliances_items_dict={"home_appliances_items": home_appliances_items}
    return render(request,'ecommerceapp/homeappliances.html', context=home_appliances_items_dict)


def cosmetic_page(request):
    cosmetic_items = models.ProductsOnSale.objects.filter(Q(productType="Cosmetic")).all()
    cosmetic_items_dict={"cosmetic_items": cosmetic_items}
    return render(request,'ecommerceapp/cosmetic.html', context=cosmetic_items_dict)

def sport_outdoor_page(request):
    sport_outdoor_items = models.ProductsOnSale.objects.filter(Q(productType="Sport Outdoor")).all()
    sport_outdoor_items_dict={"sport_outdoor_items": sport_outdoor_items}
    return render(request,'ecommerceapp/sportandoutdoor.html', context=sport_outdoor_items_dict)


def car_part_page(request):
    car_part_items = models.ProductsOnSale.objects.filter(Q(productType="Car Parts")).all()
    car_part_items_dict={"car_part_items": car_part_items}
    return render(request,'ecommerceapp/carpart.html', context=car_part_items_dict)

def garden_equipment_page(request):
    garden_equipment_items = models.ProductsOnSale.objects.filter(Q(productType="Gardan Equipment")).all()
    garden_equipment_items_dict={"garden_equipment_items": garden_equipment_items}
    return render(request,'ecommerceapp/gardenequipment.html', context=garden_equipment_items_dict)

def detail(request,pk):
    detail = models.ProductsOnSale.objects.get(pk=pk)
    detail_dict = {"detail": detail}
    return render(request, 'ecommerceapp/detail.html',context=detail_dict)


@login_required(login_url="/login")
def addbuyitem(request,pk):
    if request.POST:
        print("denee")
    else:
        models.Buyitem.objects.create(item_pk=pk,who_buy = request.user)
        return redirect('ecommerceapp:cart')
   
@login_required    
def cart(request):
    username= request.user
    items = models.Buyitem.objects.filter(Q(who_buy=username)).all()
    sonra = len(items)
    item_list=[]
    total_price= 0
    for i in range(sonra) :
        item_pk = items[i].item_pk
        item = models.ProductsOnSale.objects.get(pk=item_pk)
        item_price = item.productPrice
        total_price = total_price + item_price
        item_list.append(item)

    denemeler = total_price*0.18   
    tax = float("%.2f" % denemeler)
    row_price_calculation = total_price-tax
    row_price = float("%.2f" %  row_price_calculation)
    context={"item_list":item_list, "total_price": total_price , "tax": tax , "row_price": row_price }    
    return render(request,"ecommerceapp/cart.html", context=context)

@login_required
def deletecart(request,pk):
    models.Buyitem.objects.filter(who_buy=request.user,item_pk = pk)[0].delete()
    return redirect("ecommerceapp:cart")


@login_required(login_url="/login")
def payment (request):
    username= request.user
    items = models.Buyitem.objects.filter(Q(who_buy=username)).all()
    sonra = len(items)
    item_list=[]
    total_price= 0
    for i in range(sonra) :
        item_pk = items[i].item_pk
        item = models.ProductsOnSale.objects.get(pk=item_pk)
        item_price = item.productPrice
        total_price = total_price + item_price
        item_list.append(item)
    return render(request,"ecommerceapp/payment.html", context={"item_list": item_list,"total_price": total_price })



@login_required(login_url="/login")
def order (request):
    if request.POST:
        data= request.POST
        print(request.user)
        print(data['username'])
        if str(request.user) == str(data['username']):
            firstName= data['firstName']
            lastName= data['lastName']
            username= data['username']
            email= data['email']
            address1= data['address1']
            address2= data['address2']
            country= data['country']
            state= data['state']
            zip= data['zip']
            paymentMethod= data['paymentMethod']
            ccname= data['ccname']
            ccnumber= data['ccnumber']
            ccexpiration= data['ccexpiration']
            cccvv= data['cccvv']

            username= request.user
            items = models.Buyitem.objects.filter(Q(who_buy=username)).all()
            sonra = len(items)
            item_pk_list=[]
            total_price= 0
            for i in range(sonra) :
                item_pk = items[i].item_pk
                item = models.ProductsOnSale.objects.get(pk=item_pk)
                item_price = item.productPrice
                total_price = total_price + item_price
                item_pk_list.append(item_pk)
            

            models.OrderForm.objects.create(first_name=firstName,
                                            Last_name=lastName,
                                            username=username,
                                            email=email,
                                            address1=address1,
                                            address2=address2,
                                            country=country,
                                            state=state,
                                            zip=zip,
                                            payment=paymentMethod,
                                            name_on_card=ccname,
                                            credit_card_number=ccnumber,
                                            expiration=ccexpiration,
                                            CVV=cccvv,
                                            price= total_price,
                                            ordered_items_pk=str(item_pk_list))
            for i in item_pk_list:
                models.Buyitem.objects.filter(who_buy=username,item_pk = i).delete()
            messages.info(request,"Successfully received your order")
            return redirect("ecommerceapp:cart")
        else:
            messages.info(request, "You entered an incorrect username. Please enter correctly.")
            #mesaj eklenecek ve atılıcak
            return redirect("ecommerceapp:payment")
            
    else:
        pass    


class SignUpView(CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy("login")
    template_name = "registration/signup.html"

ecommerceproject/ecommerceapp/templates/ecommerceapp/about.html
{% extends "base.html" %}

{% block content %}

<style>
  body {
    background-image: linear-gradient(to right, #FFFFFF,#302d2d);
    
    
  }
  #deneme {
    width: 500px;
    height: 250px;
    background-color: rgb(156, 138, 138);
    
    position: absolute;
    top:0;
    bottom: 0;
    left: 0;
    right: 0;
    
    margin: auto;
}

</style>
  <div class="container" id="deneme">
    <h1>E-commerce Website</h1>
    <p>This web site is made to learn both django and python well.</p>
  </div>  


{% endblock %}

ecommerceproject/ecommerceapp/templates/ecommerceapp/cart.html
{% extends "base.html" %}

{% block content %}

{% if messages %}  
{% for message in messages %}
<div class="alert alert-success">{{ message }}</div>
{% endfor %}
{% endif %}

{% if item_list|length == 0 %}

  <div class="container" style="margin-top: 25px; margin-bottom: 40px; border: 1px solid rgb(240, 238, 238);">
    <h4 class="card-title mb-4" style="margin-left: 180px;margin-right: 180px; margin-top: 50px;">Your shopping cart is empty. OKEYYYY Let's go and buy something. 🛒</h4>
  </div>
{% else %}

<!-- cart + summary -->

<div class="container" style="margin-top: 25px; margin-bottom: 40px;">
    <div class="row no-gutters">
      <!-- cart -->
      <div class="col-lg-9">
        <div class="card border shadow-0">
          <div class="m-4">
            <h4 class="card-title mb-4">Your shopping cart</h4>
            {% for item in item_list %}
              <div class="row gy-3 mb-4">
                <div class="col-lg-5">
                  <div class="me-lg-5">
                    <div class="d-flex">
                      <img src="{{item.product_image.url}}" class="border rounded me-3" style="width: 96px; height: 96px;" />
                      <div class="">
                        <a href="/detail/{{item.pk}}" class="nav-link">{{item.productName}}</a>
                        <p class="text-muted">{{item.companyname}}</p>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="col-lg-2 col-sm-6 col-6 d-flex flex-row flex-lg-column flex-xl-row text-nowrap">
                  <div class="">
                    <text class="h6">{{item.productPrice}}&dollar;</text> <br />
                  </div>
                </div>
                <div class="col-lg col-sm-6 d-flex justify-content-sm-center justify-content-md-start justify-content-lg-center justify-content-xl-end mb-2">
                  <div class="float-md-end">
                    <a href="{% url 'ecommerceapp:deletecart' pk=item.pk %}" class="btn btn-light border text-danger icon-hover-danger"> Remove</a>
                  </div>
                </div>
              </div>
            {% endfor %}
          </div>
        </div>
      </div>
      <!-- cart -->
      <!-- summary -->
      <div class="col-lg-3">
        <div class="card shadow-0 border">
          <div class="card-body">
            <div class="d-flex justify-content-between">
              <p class="mb-2">Total price:</p>
              <p class="mb-2">{{row_price}} </p>
            </div>
            <div class="d-flex justify-content-between">
              <p class="mb-2">Discount:</p>
              <p class="mb-2 text-success">-0</p>
            </div>
            <div class="d-flex justify-content-between">
              <p class="mb-2">TAX:</p>
              <p class="mb-2">{{tax}}</p>
            </div>
            <hr />
            <div class="d-flex justify-content-between">
              <p class="mb-2">Total price:</p>
              <p class="mb-2 fw-bold">{{total_price}}</p>
            </div>
            <div class="mt-3">
              <a href="{% url 'ecommerceapp:payment' %}" class="btn btn-success w-100 shadow-0 mb-2">Make Purchase</a>
              <a href="{% url 'ecommerceapp:index' %}" class="btn btn-light w-100 border mt-2">Back to shop</a>
              
            </div>
          </div>
        </div>
      </div>
      <!-- summary -->
    </div>
  </div>
  

  <!-- cart + summary -->


{% endif %}



{% endblock %}

ecommerceproject/ecommerceapp/templates/ecommerceapp/detail.html
{% extends "base.html" %}

{% block content %}
<style>

  
  .wrapper {

    height: 750px;
    width: 1000px;
    margin: 50px auto;
    border-radius: 7px 7px 7px 7px;
    /* VIA CSS MATIC https://goo.gl/cIbnS */
    -webkit-box-shadow: 0px 14px 32px 0px rgba(0, 0, 0, 0.15);
    -moz-box-shadow: 0px 14px 32px 0px rgba(0, 0, 0, 0.15);
    box-shadow: 0px 14px 32px 0px rgba(0, 0, 0, 0.15);
  }
  
  .product-img {
    float:left;
    height: 400px;
    width: 400px;
    margin-top: 17%;
    margin-left: 15px;
  }
  
  .product-img img {
    border-radius: 7px 0 0 7px;
  }
  
  .product-info {
    float: left;
    height: 750px;
    width: 500px;
    border-radius: 0 7px 10px 7px;
    background-color: #ffffff;
  }
  
  .product-text {
    height: 300px;
    width: 327px;
  }
  
  .product-text h1 {
    margin: 0 0 0 38px;
    padding-top: 52px;
    font-size: 34px;
    color: #474747;
  }
  
  .product-text h1,
  .product-price-btn p {
    font-family: 'Bentham', serif;
  }
  
  .product-text h2 {
    margin: 0 0 47px 38px;
    font-size: 13px;
    font-family: 'Raleway', sans-serif;
    font-weight: 400;
    text-transform: uppercase;
    color: #d2d2d2;
    letter-spacing: 0.2em;
  }
  
  .product-text p {
    height: 400px;
    width: 400px;
    margin: 0 0 0 38px;
    font-family: 'Playfair Display', serif;
    color: #8d8d8d;
    line-height: 1.7em;
    font-size: 15px;
    font-weight: lighter;
    overflow: hidden;
  }
  
  .product-price-btn {
    height: 350px;
    width: 380px;
    margin-top: 200px;
    position: relative;
  }
  
  .product-price-btn p {
    display: inline-block;
    position: absolute;
    top: -13px;
    height: 50px;
    font-family: 'Trocchi', serif;
    margin: 0 0 0 38px;
    font-size: 28px;
    font-weight: lighter;
    color: #474747;
    margin-top: 12px;
  }
  
  .spanclass {
    display: inline-block;
    height: 50px;
    font-family: 'Suranna', serif;
    font-size: 34px;
  }
  
  .product-price-btn button {
    float: right;
    display: inline-block;
    height: 50px;
    width: 176px;
    margin: 0 40px 0 16px;
    box-sizing: border-box;
    border: transparent;
    border-radius: 60px;
    font-family: 'Raleway', sans-serif;
    font-size: 14px;
    font-weight: 500;
    text-transform: uppercase;
    letter-spacing: 0.2em;
    color: #ffffff;
    background-color: #9cebd5;
    cursor: pointer;
    outline: none;
  }
  
  .product-price-btn button:hover {
    background-color: #79b0a1;
  }

</style>



<div class="container-fluid">
    <div class="wrapper">
        <div class="product-img">
          <img src="{{detail.product_image.url}}" height="420" width="327">
        </div>
        <div class="product-info">
          <div class="product-text">
            <h1>{{detail.productName}}</h1>
            <h2>{{detail.companyname}}</h2>
            <p>{{detail.productdescription}}</p>
            
          </div>
          <div class="product-price-btn">
              <p><span class="spanclass">{{detail.productPrice}}</span>&dollar;</p>
            
             <button type="submit" class="button" ><a href="{% url 'ecommerceapp:addbuyitem' pk=detail.pk %}" class="button">buy now</a> </button> 

          </div>
        </div>
      </div>

</div>
 
<!--
<a href="{% url 'ecommerceapp:addbuyitem' pk=detail.pk %}" class="btn btn-danger submit">buy now</a> 
  <a href="{% url 'ecommerceapp:addbuyitem' pk=detail.pk %}">buy now</a> 
-->

{% endblock %}

ecommerceproject/ecommerceapp/templates/ecommerceapp/mainscreen.html
{% extends "base.html" %}

{% block content %}

<style>
  .bd-placeholder-img {
    font-size: 1.125rem;
    text-anchor: middle;
    -webkit-user-select: none;
    -moz-user-select: none;
    user-select: none;
  }

  @media (min-width: 768px) {
    .bd-placeholder-img-lg {
      font-size: 3.5rem;
    }
  }

  .b-example-divider {
    width: 100%;
    height: 3rem;
    background-color: rgba(0, 0, 0, .1);
    border: solid rgba(0, 0, 0, .15);
    border-width: 1px 0;
    box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
  }

  .b-example-vr {
    flex-shrink: 0;
    width: 1.5rem;
    height: 100vh;
  }

  .bi {
    vertical-align: -.125em;
    fill: currentColor;
  }

  .nav-scroller {
    position: relative;
    z-index: 2;
    height: 2.75rem;
    overflow-y: hidden;
  }

  .nav-scroller .nav {
    display: flex;
    flex-wrap: nowrap;
    padding-bottom: 1rem;
    margin-top: -1px;
    overflow-x: auto;
    text-align: center;
    white-space: nowrap;
    -webkit-overflow-scrolling: touch;
  }

  .btn-bd-primary {
    --bd-violet-bg: #712cf9;
    --bd-violet-rgb: 112.520718, 44.062154, 249.437846;

    --bs-btn-font-weight: 600;
    --bs-btn-color: var(--bs-white);
    --bs-btn-bg: var(--bd-violet-bg);
    --bs-btn-border-color: var(--bd-violet-bg);
    --bs-btn-hover-color: var(--bs-white);
    --bs-btn-hover-bg: #6528e0;
    --bs-btn-hover-border-color: #6528e0;
    --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
    --bs-btn-active-color: var(--bs-btn-hover-color);
    --bs-btn-active-bg: #5a23c8;
    --bs-btn-active-border-color: #5a23c8;
  }
  .bd-mode-toggle {
    z-index: 1500;
  }
</style>

{% load static %}
<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">


<main>

<div id="myCarousel" class="carousel slide" data-bs-ride="carousel" style="height: 650px;">
<div class="carousel-indicators">
  <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
  <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="1" aria-label="Slide 2"></button>
  <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="2" aria-label="Slide 3"></button>
</div>
<div class="carousel-inner">
  <div class="carousel-item active">
    <img src="https://images.ctfassets.net/17o2epk8ivh7/4XOfcVjU6L9Z0yxkgW0WeI/95c8ab19d73e18671e9475de046233d4/DISCOUNT_TACTICS_NEW_COLOURS_FOR_VANESSA.jpg?h=1215&q=90&w=2160" class="bd-placeholder-img" width="100%" height="100%" aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false">
    <div class="container"> 
        <div class="carousel-caption text-start">
            <h1>Now it's time to shop.</h1>
            <p>Now it's time to shop! With the discounted products on our e-commerce site, you can have the products you want while protecting your budget. Check it out now, don't miss the advantages!</p>
            <p><a class="btn btn-lg btn-primary" href="{% url 'login' %}">Sign up today</a></p>
        </div>
    </div>
  </div>
  <div class="carousel-item">
    <img src="https://st2.depositphotos.com/3246347/10607/i/600/depositphotos_106077316-stock-photo-discount-25-percent-off-3d.jpg" class="bd-placeholder-img" width="100%" height="100%" aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false">
    <div class="container">
        <div class="carousel-caption">
            <h1>Summer discounts have started!</h1>
            <p>Summer discounts have started! Here are some great opportunities to refresh your wardrobe. Discover the most trendy products of the season at discounted prices</p>
            <p><a class="btn btn-lg btn-primary" href="{% url 'login' %}">Sign up today</a></p>
        </div>
    </div>
  </div>
  <div class="carousel-item">
    <img src="https://media.smallbiztrends.com/2017/04/shutterstock_543802489.jpg" class="bd-placeholder-img" width="100%" height="100%" aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false">
    <div class="container">
        <div class="carousel-caption text-end">
            <h1>Special discounts for today only!</h1>
            <p>Special discounts for today only! Now you can buy the products you need at more affordable prices. Don't miss out!</p>
            <p><a class="btn btn-lg btn-primary" href="{% url 'login' %}">Sign up today</a></p>
        </div>
    </div>
  </div>
</div>
<button class="carousel-control-prev" type="button" data-bs-target="#myCarousel" data-bs-slide="prev" >
  <span class="carousel-control-prev-icon" aria-hidden="true"></span>
  <span class="visually-hidden">Previous</span>
</button>
<button class="carousel-control-next" type="button" data-bs-target="#myCarousel" data-bs-slide="next">
  <span class="carousel-control-next-icon" aria-hidden="true"></span>
  <span class="visually-hidden">Next</span>
</button>
</div>


<!-- Marketing messaging and featurettes
================================================== -->
<!-- Wrap the rest of the page in another container to center all the content. -->

<div class="container marketing">

<!-- Three columns of text below the carousel -->
<div class="row" style="margin-left: 60px; margin-top: 20px;" >
  <div class="col-lg-4">
    <img class="bd-placeholder-img rounded-circle" width="140" height="140" src="https://media.istockphoto.com/id/874826500/tr/foto%C4%9Fraf/ak%C4%B1ll%C4%B1-tv-ak%C4%B1ll%C4%B1-telefon-dijital-tablet-ve-diz%C3%BCst%C3%BC-bilgisayar-yans%C4%B1t%C4%B1c%C4%B1-y%C3%BCzeyi.jpg?s=170667a&w=0&k=20&c=tUNKqMdqirZgjNV1cwF7nWr7fgKQI3DCs9XAMQuFbcM=" class="bd-placeholder-img" width="100%" height="100%" aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false">
    <h2 class="fw-normal">Electronic</h2>
    <p>Electronic products are on sale with discounts. You can find the latest technologies below.</p>
    <p><a class="btn btn-secondary" href="{% url 'ecommerceapp:electronic' %}">View details &raquo;</a></p>
  </div><!-- /.col-lg-4 -->
  <div class="col-lg-4">
    <img class="bd-placeholder-img rounded-circle" width="140" height="140" src="https://iatkv.tmgrup.com.tr/6f0d18/0/0/0/0/0/0?u=https%3A%2F%2Fitkv.tmgrup.com.tr%2Falbum%2F2022%2F04%2F02%2F1648910269493.jpg&mw=400&l=1" class="bd-placeholder-img" width="100%" height="100%" aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false">
    <h2 class="fw-normal">Clothes</h2>
    <p>New fashion clothes on our site. You can find your style with very beautiful colors and varieties.</p>
    <p><a class="btn btn-secondary" href="{% url 'ecommerceapp:clothes' %}">View details &raquo;</a></p>
  </div><!-- /.col-lg-4 -->
  <div class="col-lg-4">
    <img class="bd-placeholder-img rounded-circle" width="140" height="140" src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQP3t0HhlnmmSBNUmHUPznrEERSG1IxplTCfw&usqp=CAU" class="bd-placeholder-img" width="100%" height="100%" aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false">
    <h2 class="fw-normal">Car parts</h2>
    <p>You can add style to your style with new parts to your cars. Bring your car to life with our catalog of many products.</p>
    <p><a class="btn btn-secondary" href="{% url 'ecommerceapp:carpart' %}">View details &raquo;</a></p>
  </div><!-- /.col-lg-4 -->
</div><!-- /.row -->


<!-- START THE FEATURETTES -->

<hr class="featurette-divider">

<div class="row featurette">
  <div class="col-md-7">
    <h2 class="featurette-heading fw-normal lh-1">Now it's time to shop!</h2>
    <p class="lead">Now it's time to shop! With the discounted products on our e-commerce site, you can have the products you want while protecting your budget. Check it out now, don't miss the advantages!</p>
  </div>
  <div class="col-md-5">
    <img src="https://images.ctfassets.net/17o2epk8ivh7/4XOfcVjU6L9Z0yxkgW0WeI/95c8ab19d73e18671e9475de046233d4/DISCOUNT_TACTICS_NEW_COLOURS_FOR_VANESSA.jpg?h=1215&q=90&w=2160" class="bd-placeholder-img" width="100%" height="100%" aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false">
  </div>
</div>

<hr class="featurette-divider">

<div class="row featurette">
  <div class="col-md-7 order-md-2">
    <h2 class="featurette-heading fw-normal lh-1">Summer discounts have started!</span></h2>
    <p class="lead">Summer discounts have started! Here are some great opportunities to refresh your wardrobe. Discover the most trendy products of the season at discounted prices</p>
  </div>
  <div class="col-md-5 order-md-1">
    <img src="https://st2.depositphotos.com/3246347/10607/i/600/depositphotos_106077316-stock-photo-discount-25-percent-off-3d.jpg" class="bd-placeholder-img" width="100%" height="100%" aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false">
  </div>
</div>

<hr class="featurette-divider">

<div class="row featurette">
  <div class="col-md-7">
    <h2 class="featurette-heading fw-normal lh-1">Special discounts for today only!</span></h2>
    <p class="lead">Special discounts for today only! Now you can buy the products you need at more affordable prices. Don't miss out!</p>
  </div>
  <div class="col-md-5">
    <img src="https://media.smallbiztrends.com/2017/04/shutterstock_543802489.jpg" class="bd-placeholder-img" width="100%" height="100%" aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false">
  </div>
</div>

<hr class="featurette-divider">

<!-- /END THE FEATURETTES -->

</div><!-- /.container -->





{% endblock %}